spring:
  datasource:
    url: jdbc:postgresql://118.25.193.38:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  #多项目部署时用到的
  jmx:
      enabled: false

server:
  port: 8011
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /passport

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO